### ISSUE TITLE
Video Files

### ISSUE THREAD

**Issue by blownco** [tardisx/discord-auto-upload#15]
Is there a way this can be used for video files?

I'd like to upload replays from my stream to my discord.

**Comment by tardisx** [comment]
Hi @blownco,

I've considered it, but the Discord maximum upload size (8mb) seems to make it impractical - it's no more than a few seconds of a typical 1920x1080 capture.

Also, while image screen captures can typically be uploaded "as is", video files seem more likely to need tweaking (trim, re-encode and so on) which make it seem less compatible with the immediacy of normal discord-auto-upload use (spamming images, typically :-) 

I'm going to close this, but if you think you have a valid use-case within those limitations, please do update with more details on your use-case.
