### ISSUE TITLE
[Suggestion] Multiple Instances

### ISSUE THREAD

**Issue by Nikolai-RR** [tardisx/discord-auto-upload#16]
I would love to see an option to either have multiple instances watching mutiple folders, uploading to their own webhooks, or having one instance with mutiple folder/webhook pairs.

**Comment by ngkienmkqn** [comment]
https://drive.google.com/drive/folders/1jpPJCrfV5Ba9fRZCocBh_NV6FcSEsPnt?usp=sharing

**Comment by Nikolai-RR** [comment]
Err... the folder is empty.

**Comment by tardisx** [comment]
The next release will support multiple watchers from a single instance.

**Comment by Nikolai-RR** [comment]
I presume 8483fe7 is related to this?

**Comment by tardisx** [comment]
Yes, but please wait for a stable release version as the work is not yet complete.

**Comment by tardisx** [comment]
v0.11.0 is now released :-)
