### ISSUE TITLE
Fails to send attachement

### ISSUE THREAD

**Issue by megahypercat** [tardisx/discord-auto-upload#2]
![mpc-hc64_2018-06-12_11-12-49 1](https://user-images.githubusercontent.com/31746936/41281420-9f81f1fe-6e31-11e8-9c90-753864c269e7.png)

**Comment by megahypercat** [comment]
Don't worry about the token, it's a test server anyways.

**Comment by tardisx** [comment]
I'm working on improving the logging for these sorts of problems.

I'd guess this is due to hitting the (discord) upload size limit, though I'm not sure exactly what that limit is at the moment.

**Comment by tardisx** [comment]
Sorry for the delay in looking at this.

If the upload is too large, you should see something like this:

```
2021/01/31 10:08:31 Bad response from server:413
2021/01/31 10:08:31 Body:{"message": "Request entity too large", "code": 40005}
```

If it's something else, I would appreciate getting a copy of an image that doesn't work, so I can test. I'm closing this, but feel free to reopen.
