### ISSUE TITLE
Stopped uploading images to my discord

### ISSUE THREAD

**Issue by JudgedDreddful** [tardisx/discord-auto-upload#20]
for some strange reason this wonderful applet stopped uploading images to my discord channel/server, i tried resetting it reinstallin it even a different webhook but nothing

**Comment by tardisx** [comment]
Hi @JudgedDreddful , glad you think it's wonderful :-)

There should be some information on the logs (check the window where it is running and also the logs tab in the web interface). 

If you can find some info there it would be helpful to see what is going on. 

If there is nothing at all, I'd suggest the thing to check is that it is pointing to the correct path for your screenshots.

**Comment by JudgedDreddful** [comment]
Thanks for the reply I sorted it out, I suspect an update from Windows had
a hand in it or firewall issue. I basically unusually everything even "Go",
rebooted, reinstalled to a new folder location, Rebooted and everything
worked great. Took a few attempts but that resolved my situation.

Thanks again
Don
