### ISSUE TITLE
idk if it is just me but dau never work for me, it never read any files on my PC and upload them to discord, would love to get some help!

### ISSUE THREAD

**Issue by dungndgcd201420** [tardisx/discord-auto-upload#22]
![image](https://user-images.githubusercontent.com/100248638/157594065-fa8ddad9-e27a-4448-a195-164543a50cdf.png)

**Comment by tardisx** [comment]
Files are detected by modification time. If you drag an existing file in from somewhere else on your disk, it will not be considered "new". Try opening a file and "Save As" it into that folder.

**Comment by dungndgcd201420** [comment]
Thanks this help a lot
