### ISSUE TITLE
[Suggestion] Hidden window or minimize to tray

### ISSUE THREAD

**Issue by th3jesta** [tardisx/discord-auto-upload#23]
Would love a way to hide the application window. A tray icon with a shortcut to the webpage would be great.

**Comment by tardisx** [comment]
Hi, thanks for the suggestion!

This is definitely on my roadmap. I'll leave this issue open for tracking.

**Comment by tardisx** [comment]
Probably via https://github.com/getlantern/systray

**Comment by th3jesta** [comment]
Need an icon? I have an idea for one.

**Comment by tardisx** [comment]
Yes, please :-)

**Comment by th3jesta** [comment]
Here's a concept I threw together that was floating around in my brain. 

![DAU-Icon](https://user-images.githubusercontent.com/38670315/161458833-9bd8fb1e-46ea-49dc-8b88-2dc70a6980f7.png)

**Comment by jh-chrysos** [comment]
Thank you - I like it a lot. Would you be happy for me to use it on the discord server as well?

**Comment by tardisx** [comment]
Thank you - I like it a lot. Would you be happy for it to be used for the discord server as well?

**Comment by th3jesta** [comment]
Let's hold off for a minute. I have some additional tweaks I want to make to it if that's okay. Thanks for the consideration!

**Comment by tardisx** [comment]
Yes, no rush. I have some groundwork to do before I need it :-)

**Comment by th3jesta** [comment]
How about this?
![DAU-Icon-02](https://user-images.githubusercontent.com/38670315/161468100-3c1a1bbf-02c4-4fb4-8a16-c33fb52f6641.png)

**Comment by th3jesta** [comment]
Not sure which one I like better.

**Comment by tardisx** [comment]
I like it, do you think the finer detail will be a problem once it is systray-sized ?

**Comment by th3jesta** [comment]
I think you're right. I like the simplicity of the first better, and it
should scale to tray-size better.

**Comment by tardisx** [comment]
Shiny new version v0.12.2 with tray icon and no console window (on windows) now available. 

Thanks @th3jesta for the icon. I apologise that I currently do not have a formal place for acknowledgements at the moment - I will repair that soon.
