### ISSUE TITLE
[Suggestion] add network support

### ISSUE THREAD

**Issue by Midnight-NOW** [tardisx/discord-auto-upload#32]
if you have multiple pcs on the network and have to open ports on your pc set the IP on the device you are trying to get photos from
to send in a discord.
so you don't have to start or think is it up the server pc will run it for you.
and don't have to tell hey get this app to auto send photos for you.

-if can make it work with IP's, Could you find the file path of consoles? and auto send them.

**Comment by tardisx** [comment]
Hi @Midnight-NOW , if I'm understanding correctly, you're proposing that dau be able to "see" files on other systems on the network.

I'm afraid that's pretty unlikely to happen, there is no common interface to access remote systems like that.

You could mount a network share on whatever device you are running dau on and point a watcher at that, but it depends on the remote machine as to what is available, and it's well outside the scope of dau.
