### ISSUE TITLE
Double Image

### ISSUE THREAD

**Issue by IonizedRadiation** [tardisx/discord-auto-upload#6]
I just started using this tool (it works wonderfully) but I have one question about what it is doing.  When the webhook sends the messages that it sends, it ends up sending 2 images; the screenshot, and a second, lower quality image with a giant watermark on it. Is that supposed to happen?

**Comment by tardisx** [comment]
That's pretty odd! Is it consistent? Are you able to provide some logs?

**Comment by tardisx** [comment]
Oh I understand now. The second image will be a thumbnail which was probably generated by steam (or whatever you have making screenshots) in the sub directory, or a subdirectory of that watch directory.

The 'exclude' option will help you here.

**Comment by Bonhovis** [comment]
Hi @tardisx :) I've just started using this tool. It works wonderfully, although I'm also experiencing this issue where it also uploads the thumbnail created by Steam (from a \Thumbnails\ sub-directory where the screenshot is located).

I see in the documentation and above that you've mentioned using the 'exclusions' functionality to filter these out but, unless I've missed it, it's unclear to me how I should be stating this exclusion (e.g. I would ideally like to exclude any file that's in a directory called Thumbnails). The thumbnail and image itself share the same filename and format. I tried something like "*\Thumbnails\*" but this didn't seem to work.

Any ideas? Is this possible? Many thanks in advance.

**Comment by tardisx** [comment]
Hi @Bonhovis - exclusions are simple string matches. If all thumbnails contain the string 'thumbnail', then just using that as the exclusion should work. The string is checked against the entire fully-qualified path, so it will match against the filename or a directory name.

**Comment by Bonhovis** [comment]
> Hi @Bonhovis - exclusions are simple string matches. If all thumbnails contain the string 'thumbnail', then just using that as the exclusion should work. The string is checked against the entire fully-qualified path, so it will match against the filename or a directory name.

Thanks @tardisx - Looks like I was just overthinking it and thought I'd need to use wildcards, when I didn't need to! Thanks for your help. Great application, I love it 😄
