### ISSUE TITLE
No watermark

### ISSUE THREAD

**Issue by DroidXAce** [tardisx/discord-auto-upload#7]
Hello,

I would like to remove the watermark on the image, but I don't know how to use the "--no-watermark" field in my "dau.bat" file.
How do I indicate it please?

**Comment by Baoulettes** [comment]
Hi, edit the .bat with the follow line : 

`dau.exe --no-watermark --webhook %WEBHOOK_URL% --directory %SCREENSHOTS% --username %USERNAME% --watch %WATCH%`
Work fine for me :)

**Comment by tardisx** [comment]
Thanks @Baoulettes
