### ISSUE TITLE
Dependencies "assets"

### ISSUE THREAD

**Issue by Baoulettes** [tardisx/discord-auto-upload#8]
Hi, 
Wanted to build a custom build with restriction, like only upload a certain type of file name and with or without check data modification. 
But during building I had that issues and unsure what the proper dependency is : 
server.go line : 8
"github.com/tardisx/discord-auto-upload/assets"
Would you mind giving a clue what is it beside Sparta eheh

**Comment by tardisx** [comment]
Hi, yes the build hasn't been done for a few years and things have moved on. I will see if I can repair things soon :-)

**Comment by tardisx** [comment]
README.md fixed in #55bb5a8bae715b1840a29ca3b17b65652e97707b
