### ISSUE TITLE
.exe won't run

### ISSUE THREAD

**Issue by sammyboy816** [tardisx/discord-auto-upload#9]
Hello!

So, I recently downloaded this program, and have been able to get things working using the .bat file, but haven't had any luck getting the .exe file to run. I want to do that because I want to be able to turn off the water markings on the image, and there isn't an option to do that in the .bat file. 

I don't have any log files or anything to share (I know that you might not be able to help without them, and that's fine. Just figured I would reach out). But what will basically happen is I will click the .exe file, and then it will flash up in the task bar for just a blip and then disappear. Do you know what this might be happening? It also won't let me go to http://localhose:9090 to configure anything, which I figure that's because the .exe file isn't opened.

Any tips? I haven't tried compiling the code myself yet because I don't know too much about all of that. But if you help me out in any way, I would appreciate it.

Regards,
Sam

**Comment by sammyboy816** [comment]
I figured it out. I just went in and edited the .bat file and added the --no-watermark bit to it.

**Comment by sammyboy816** [comment]
Here is what my .bat file looks like in case anyone is wanting to know how to do it.

set WEBHOOK_URL=https://discordapp.com/api/webhooks/[WEBHOOK URL]
set SCREENSHOTS="C:\Users\PATH_TO_FILE
set USERNAME="NAME_OF_BOT"
set WATCH=10
set NOWATERMARK=true
dau.exe --webhook %WEBHOOK_URL% --directory %SCREENSHOTS% --username %USERNAME% --watch %WATCH% --no-watermark %NOWATERMARK%
pause

**Comment by tardisx** [comment]
That was a rollercoaster :-)

For reference, the web interface is only in the develop version, not a released one yet (coming real soon now) - it will enable you to do away with .bat files.

It will still have an option to remove the watermark, though I weep when you enable it :-D

**Comment by tardisx** [comment]
Hi @sammyboy816 , the new version with web configuration support is now available.
